name: model-training
on: 
    push:
      branches:
         - master

jobs:

  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Test model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          pip install -r requirements.txt

          # Pull data & run-cache from S3 and reproduce pipeline
          dvc pull data/winequality-red-test.csv.dvc --run-cache
          #dvc pull data --run-cache
          #dvc repro
          python test.py

          
          git config --global user.name "simithcollege"
          git config --global user.email "73145893+simithcollege@users.noreply.github.com"

          git add model/model.pkcl && git commit -m "generate model file" --allow-empty
          git push origin master

          cat metrics.txt >> report.md
          cml-publish confusion_matrix.png --md >> report.md
          cml-send-comment report.md

      - uses: andstor/copycat-action@v3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: /model/
          dst_path: /model/
          dst_owner: simithcollege
          dst_repo_name: prodserver
          dst_branch: master
          src_branch: master
          username: simithcollege
          email: 'larry.lecomte@gmail.com'